name: DartPolymerCodeLabKrakow
description: A sample Polymer application
dependencies:
  core_elements: ">=0.4.0+3 <0.5.0"
  polymer: '>=0.15.1 <0.16.0'
  paper_elements: ">=0.5.0 <0.6.0"
transformers:
- polymer:
    entry_points:
      - web/step_01/index.html
      - web/step_02/index.html
      - web/step_03/index.html
      - web/step_04/index.html
      - web/step_05/index.html
      - web/step_06/index.html
